---
- hosts: sim
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    # kernel_type can be "realtime" or "gtp"
    - { role: kernel-install, kernel_type: realtime, update_all: true }
