---

# ### Building openair-cn
#     sudo yum install git
#     git clone https://gitlab.eurecom.fr/oai/openair-cn.git
#     cd openair-cn
#     git checkout feature-53-support-enterprise-linux-7-develop
#     cd scripts
#     ./build_hss -i
#     mysqladmin -u root password linux
#         #configure ../etc/hss.conf
#         #    set MYSQL_user to "root" and MYSQL_pass to "linux"
#     sudo cp ../etc/hss.conf /usr/local/etc/oai/
#     sudo cp ../etc/acl.conf ../etc/hss_fd.conf /usr/local/etc/oai/freeDiameter/
#         #configure /etc/hosts
#         #    add those two lines:
#         #    127.0.1.1   epc.openair4G.eur epc
#         #    127.0.1.1   hss.openair4G.eur hss
#     ./check_hss_s6a_certificate /usr/local/etc/oai/freeDiameter hss.openair4G.eur
#     ./build_hss
#     ./run_hss -i ../src/oai_hss/db/oai_db.sql 
#         #ctrl+c now, this first run was to import the DB
#     ./build_mme -i
#         #configure ../etc/mme.conf
#         #    set MME_IPV4_ADDRESS_FOR_S1_MME to "10.0.1.2/24"
#     sudo cp ../etc/mme.conf /usr/local/etc/oai/
#         #configure ../etc/mme_fd.conf
#         #    set Identity to "epc.openair4G.eur"
#     sudo cp ../etc/mme_fd.conf /usr/local/etc/oai/freeDiameter/
#     ./build_mme
#     ./check_mme_s6a_certificate /usr/local/etc/oai/freeDiameter epc.openair4G.eur
#     ./build_spgw -i
#         #configure ../etc/spgw.conf
#         #    set SGW_IPV4_ADDRESS_FOR_S1U_S12_S4_UP to "10.0.1.2/24"
#         #    set PGW_INTERFACE_NAME_FOR_SGI to "eth0"
#         #    optionally set PGW_MASQUERADE_SGI to "yes"
#         #    optionally sett UE_TCP_MSS_CLAMPING to "yes"
#         #    check DEFAULT_DNS_IPV4_ADDRESS and DEFAULT_DNS_SEC_IPV4_ADDRESS
#     sudo cp ../etc/spgw.conf /usr/local/etc/oai/
#     ./build_spgw
#     mysql -u root -p
#     use oai_db;
#     update mmeidentity set mmehost="epc.openair4G.eur" where idmmeidentity=4;
#     quit;
#     systemctl disable firewalld
#     systemctl stop firewalld
- name: Install epel
  yum:
    name: epel-release
    state: installed

- name: Yum install deps (for OAI compilation)
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - psmisc
    - cmake3
    - cmake
    - autoconf
    - automake
    - bison
    - doxygen
    - flex
    - gdb
    - subversion
    - gnutls-devel
    - libconfig-devel
    - libgcrypt-devel
    - libidn-devel
    - libidn2-devel
    - libtool
    - lksctp-tools
    - lksctp-tools-devel
    - mariadb-devel
    - nettle-devel
    - openssl-devel
    - gcc-c++
    - libxml2-devel
    - mercurial
    - swig
    - pexpect
    - phpMyAdmin


- name: Clone openair-cn
  git:
    repo: https://gitlab.eurecom.fr/oai/openair-cn.git
    dest: /usr/src/openair-cn
    version: "{{ openaircn_version }}"

- name: Run build_hss script (in "install dependencies mode" [doesn't build hss.])
  shell: >
    yes | ./build_hss -i
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /etc/.build_hss-deps-complete

- name: Mark build_hss dependencies complete.
  file:
    dest: /etc/.build_hss-deps-complete
    state: directory

- name: template hss.conf
  template:
    src: hss.conf.j2
    dest: /usr/local/etc/oai/hss.conf

- name: Copy files into proper locations
  shell: >
    cp -f {{ item.src }} {{ item.dest }}
  args:
    creates: "{{ item.dest }}"
  with_items:
    - src: /usr/src/openair-cn/etc/acl.conf
      dest: /usr/local/etc/oai/freeDiameter/acl.conf
    - src: /usr/src/openair-cn/etc/hss_fd.conf
      dest: /usr/local/etc/oai/freeDiameter/hss_fd.conf

- name: Build hss certs
  shell: >
    ./check_hss_s6a_certificate /usr/local/etc/oai/freeDiameter hss.openair4G.eur
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /usr/local/etc/oai/freeDiameter/hss.cert.pem

- name: Run build_hss proper (actually builds binary)
  shell: >
    ./build_hss
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /usr/local/bin/oai_hss

# Run hss...
# says... Unknown database 'oai_db'

- name: Create a new database with name 'bobdata'
  mysql_db:
    name: bobdata
    state: present
