---

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Install epel
  yum:
    name: epel-release
    state: installed

- name: Yum install deps (for OAI compilation)
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - psmisc
    - cmake3
    - cmake
    - autoconf
    - automake
    - bison
    - doxygen
    - flex
    - gdb
    - subversion
    - gnutls-devel
    - libconfig-devel
    - libgcrypt-devel
    - libidn-devel
    - libidn2-devel
    - libtool
    - lksctp-tools
    - lksctp-tools-devel
    - mariadb-devel
    - nettle-devel
    - openssl-devel
    - gcc-c++
    - libxml2-devel
    - mercurial
    - swig
    - pexpect
    - phpMyAdmin
    - check
    - check-devel
    - gtk3-devel
    - guile-devel
    - gccxml
    - iperf

- name: Clone openair-cn
  git:
    repo: https://gitlab.eurecom.fr/oai/openair-cn.git
    dest: /usr/src/openair-cn
    version: "{{ openaircn_version }}"

- name: Run build_hss script (in "install dependencies mode" [doesn't build hss.])
  shell: >
    yes | ./build_hss -i
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /etc/.build_hss-deps-complete

- name: Mark build_hss dependencies complete.
  file:
    dest: /etc/.build_hss-deps-complete
    state: directory

- name: template oai configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: hss.conf.j2
      dest: /usr/local/etc/oai/hss.conf
    - src: mme.conf.j2
      dest: /usr/local/etc/oai/mme.conf
    - src: mme_fd.conf.j2
      dest: /usr/local/etc/oai/freeDiameter/mme_fd.conf
    - src: spgw.conf.j2
      dest: /usr/local/etc/oai/spgw.conf

- name: Copy configs (for freeDiameter) into proper locations
  shell: >
    cp -f {{ item.src }} {{ item.dest }}
  args:
    creates: "{{ item.dest }}"
  with_items:
    - src: /usr/src/openair-cn/etc/acl.conf
      dest: /usr/local/etc/oai/freeDiameter/acl.conf
    - src: /usr/src/openair-cn/etc/hss_fd.conf
      dest: /usr/local/etc/oai/freeDiameter/hss_fd.conf

- name: Build hss certs
  shell: >
    ./check_hss_s6a_certificate /usr/local/etc/oai/freeDiameter hss.openair4G.eur
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /usr/local/etc/oai/freeDiameter/hss.cert.pem

- name: Run build_hss proper (actually builds binary)
  shell: >
    ./build_hss
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /usr/local/bin/oai_hss

- name: Show oai_db tables
  shell: >
    mysql oai_db -e 'SHOW TABLES;'
  register: oaidb_tables

# We have to kill this command, so, we give it 10 seconds to complete.
# Downside, it exists with 124 when it's doing the right thing.
- name: Run the run_hss in intialization mode (which creates tables)
  shell: >
    timeout 10 ./run_hss -i ../src/oai_hss/db/oai_db.sql &> /dev/null
  ignore_errors: yes
  args:
    chdir: /usr/src/openair-cn/scripts
  when: "'users' not in '{{ oaidb_tables.stdout }}'"

- name: Run build_mme (in intialization mode)
  shell: >
    yes | ./build_mme -i
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /etc/.build_mme-deps-complete
  
- name: Mark build_mme dependencies complete.
  file:
    dest: /etc/.build_mme-deps-complete
    state: directory

- name: Run build_mme (proper)
  shell: >
    ./build_mme
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /usr/local/bin/mme

- name: Check mme certificates
  shell: >
    ./check_mme_s6a_certificate /usr/local/etc/oai/freeDiameter epc.openair4G.eur
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /usr/local/etc/oai/freeDiameter/mme.key.pem

- name: Run build_spgw (in intialization mode)
  shell: >
    yes | ./build_spgw -i
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /etc/.build_spgw-deps-complete

- name: Mark build_spgw dependencies complete.
  file:
    dest: /etc/.build_spgw-deps-complete
    state: directory

- name: Run build_spgw (proper)
  shell: >
    ./build_spgw
  args:
    chdir: /usr/src/openair-cn/scripts
    creates: /usr/local/bin/spgw

- name: Check values in oai_db.mmeidentity
  shell: >
    mysql oai_db -e 'SELECT * FROM mmeidentity WHERE idmmeidentity=4';
  register: oaidb_identity

- name: Update oai_db.mmeidentity
  shell: >
    mysql oai_db -e 'UPDATE mmeidentity SET mmehost="epc.openair4G.eur" WHERE idmmeidentity=4;'
  when: "'epc.openair4G.eur' not in oaidb_identity.stdout" 

